name: CDK Deployment
on:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet
        default : Selassiee
    branches:
      - main      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          sudo rm -f /usr/local/bin/aws
          sudo ln -s /usr/local/aws-cli/v2/current/bin/aws /usr/local/bin/aws

      - name: Install CDK
        run: npm install -g aws-cdk

